{% set name = "diffpy.pdfgui" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://test.pypi.io/packages/source/d/diffpy_pdfgui/diffpy_pdfgui-{{ version }}.tar.gz
  sha256: cd64ed0e17de7ec02ce15ca568833f54310c529879ead4189a48954bf7a3902b

build:
  # we need egg_dir to avoid overlapping diffpy/__init__.py files.
  preserve_egg_dir: true
  number: 0
  skip: true  # [py<310]
#  noarch: python
#  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - pdfgui = diffpy.pdfgui.applications.pdfgui:main
  osx_is_app: true

requirements:
  host:
    - python
    - pip
    - setuptools
    - setuptools-git-versioning >=2.0
  run:
    - python
    - setuptools
    - six
    - matplotlib
    - wxpython =4.2.1=py310h2693ab4_5  # [osx64 and py==310]
    - wxpython =4.2.1=py311ha82924a_5  # [osx64 and py==311]
    - wxpython =4.2.1=py312hba984fc_5  # [osx64 and py==312]
    - wxpython =4.2.1=py310h8348223_5  # [linux and py==310]
    - wxpython =4.2.1=py311h35114c6_5  # [linux and py==311]
    - wxpython =4.2.1=py312h7c8d89b_5  # [linux and py==312]
    - wxpython =4.2.1=py310h00ffb61_5  # [win and py==310]
    - wxpython =4.2.1=py311h12c1d0e_5  # [win and py==311]
    - wxpython =4.2.1=py312h53d5487_5  # [win and py==312]
    - menuinst  # [win]
    - diffpy.pdffit2
    - diffpy.structure
    - diffpy.utils

test:
  requires:
    - pip
    - pytest
  source_files:
    - tests
  commands:
    - conda list
    - pip list
    - pytest

app:
  entry: pdfgui  # [not win]
  entry: pythonw -m diffpy.pdfgui.applications.pdfgui  # [win]
  icon: pdfgui_64x64.png
  summary: materials structure analysis from Pair Distribution Function

about:
  home: https://github.com/diffpy/diffpy.pdfgui
  summary: GUI for PDF simulation and structure refinement
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  description: |
    The diffpy.pdfgui package provides a graphical user interface to pdffit2 refinement engine, 
    with many powerful extensions. It is a GUI program for structure refinements to atomic pair 
    distribution function. It is capable of full-profile fitting of the atomic pair distribution 
    function derived from x-ray or neutron diffraction data and comes with built in graphical and 
    structure visualization capabilities.
  doc_url: https://www.diffpy.org/products/pdfgui.html
  dev_url: https://github.com/diffpy/diffpy.pdfgui

extra:
  recipe-maintainers:
    - bobleesj
    - dragonyanglong
    - sbillinge
